// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mate.Data;

#nullable disable

namespace mate.Data.Migrations
{
    [DbContext(typeof(mateDbContext))]
    partial class mateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mate.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JudgeSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TagsJson");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JudgeSettingId");

                    b.HasIndex("TenantId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("mate.Domain.Entities.AgentConnectorConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentConnectorConfigs");
                });

            modelBuilder.Entity("mate.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Prefix");

                    b.HasIndex("TenantId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("mate.Domain.Entities.AppSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSecrets");
                });

            modelBuilder.Entity("mate.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("mate.Domain.Entities.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("bytea");

                    b.Property<double?>("EndChapter")
                        .HasColumnType("double precision");

                    b.Property<double?>("StartChapter")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ChunkIndex");

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("mate.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("mate.Domain.Entities.GlobalQuestionGenerationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyRef")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<double>("TopP")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("GlobalQuestionGenerationSettings");
                });

            modelBuilder.Entity("mate.Domain.Entities.JudgeSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndpointRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double>("FactualityWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("HelpfulnessWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("IntentMatchWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("PassThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("PromptTemplate")
                        .HasColumnType("text");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("SafetyWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("TaskSuccessWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<double>("TopP")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseReferenceAnswer")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("JudgeSettings");
                });

            modelBuilder.Entity("mate.Domain.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CitationsJson");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FactualityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("HelpfulnessScore")
                        .HasColumnType("double precision");

                    b.Property<string>("HumanVerdict")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("HumanVerdictAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HumanVerdictBy")
                        .HasColumnType("text");

                    b.Property<string>("HumanVerdictNote")
                        .HasColumnType("text");

                    b.Property<double>("IntentMatchScore")
                        .HasColumnType("double precision");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Rationale")
                        .HasColumnType("text");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<double>("SafetyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("TaskSuccessScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("mate.Domain.Entities.RubricCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EvaluationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RubricSetId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RubricSetId");

                    b.ToTable("RubricCriterias");
                });

            modelBuilder.Entity("mate.Domain.Entities.RubricSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JudgeSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("RequireAllMandatory")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SourceRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JudgeSettingId");

                    b.ToTable("RubricSets");
                });

            modelBuilder.Entity("mate.Domain.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageLatencyMs")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<double>("MedianLatencyMs")
                        .HasColumnType("double precision");

                    b.Property<double>("P95LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<int>("PassedCount")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalTestCases")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("SuiteId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("mate.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalTenantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("mate.Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("text");

                    b.Property<int>("MaxAgents")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMonthlyRuns")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTestCasesPerSuite")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTestSuites")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyRunsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSubscriptions");
                });

            modelBuilder.Entity("mate.Domain.Entities.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ExternalUserId")
                        .IsUnique();

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedEntities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExpectedEntitiesJson");

                    b.Property<string>("ExpectedIntent")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ReferenceAnswer")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("TagsJson");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserInputJson");

                    b.HasKey("Id");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("SuiteId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DelayBetweenTestsMs")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JudgeSettingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("PassThreshold")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JudgeSettingId");

                    b.HasIndex("TenantId");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestSuiteAgent", b =>
                {
                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("TestSuiteId", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("TestSuiteAgents");
                });

            modelBuilder.Entity("mate.Domain.Entities.TranscriptMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RawActivityJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TurnIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResultId", "TurnIndex");

                    b.ToTable("TranscriptMessages");
                });

            modelBuilder.Entity("mate.Domain.Entities.Agent", b =>
                {
                    b.HasOne("mate.Domain.Entities.JudgeSetting", "JudgeSetting")
                        .WithMany()
                        .HasForeignKey("JudgeSettingId");

                    b.HasOne("mate.Domain.Entities.Tenant", null)
                        .WithMany("Agents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JudgeSetting");
                });

            modelBuilder.Entity("mate.Domain.Entities.AgentConnectorConfig", b =>
                {
                    b.HasOne("mate.Domain.Entities.Agent", "Agent")
                        .WithMany("ConnectorConfigs")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("mate.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("mate.Domain.Entities.Tenant", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mate.Domain.Entities.Chunk", b =>
                {
                    b.HasOne("mate.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("mate.Domain.Entities.Document", b =>
                {
                    b.HasOne("mate.Domain.Entities.Tenant", null)
                        .WithMany("Documents")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mate.Domain.Entities.JudgeSetting", b =>
                {
                    b.HasOne("mate.Domain.Entities.Tenant", null)
                        .WithMany("JudgeSettings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mate.Domain.Entities.Result", b =>
                {
                    b.HasOne("mate.Domain.Entities.Run", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mate.Domain.Entities.TestCase", "TestCase")
                        .WithMany("Results")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("mate.Domain.Entities.RubricCriteria", b =>
                {
                    b.HasOne("mate.Domain.Entities.RubricSet", "RubricSet")
                        .WithMany("Criteria")
                        .HasForeignKey("RubricSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RubricSet");
                });

            modelBuilder.Entity("mate.Domain.Entities.RubricSet", b =>
                {
                    b.HasOne("mate.Domain.Entities.JudgeSetting", "JudgeSetting")
                        .WithMany("RubricSets")
                        .HasForeignKey("JudgeSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JudgeSetting");
                });

            modelBuilder.Entity("mate.Domain.Entities.Run", b =>
                {
                    b.HasOne("mate.Domain.Entities.Agent", "Agent")
                        .WithMany("Runs")
                        .HasForeignKey("AgentId");

                    b.HasOne("mate.Domain.Entities.TestSuite", "Suite")
                        .WithMany("Runs")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("mate.Domain.Entities.TenantSubscription", b =>
                {
                    b.HasOne("mate.Domain.Entities.Tenant", "Tenant")
                        .WithOne("Subscription")
                        .HasForeignKey("mate.Domain.Entities.TenantSubscription", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("mate.Domain.Entities.TenantUser", b =>
                {
                    b.HasOne("mate.Domain.Entities.Tenant", null)
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mate.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("mate.Domain.Entities.Document", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId");

                    b.HasOne("mate.Domain.Entities.TestSuite", "Suite")
                        .WithMany("TestCases")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceDocument");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestSuite", b =>
                {
                    b.HasOne("mate.Domain.Entities.JudgeSetting", "JudgeSetting")
                        .WithMany()
                        .HasForeignKey("JudgeSettingId");

                    b.HasOne("mate.Domain.Entities.Tenant", null)
                        .WithMany("TestSuites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JudgeSetting");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestSuiteAgent", b =>
                {
                    b.HasOne("mate.Domain.Entities.Agent", "Agent")
                        .WithMany("TestSuiteAgents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mate.Domain.Entities.TestSuite", "TestSuite")
                        .WithMany("TestSuiteAgents")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("mate.Domain.Entities.TranscriptMessage", b =>
                {
                    b.HasOne("mate.Domain.Entities.Result", "Result")
                        .WithMany("Transcript")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("mate.Domain.Entities.Agent", b =>
                {
                    b.Navigation("ConnectorConfigs");

                    b.Navigation("Runs");

                    b.Navigation("TestSuiteAgents");
                });

            modelBuilder.Entity("mate.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("mate.Domain.Entities.JudgeSetting", b =>
                {
                    b.Navigation("RubricSets");
                });

            modelBuilder.Entity("mate.Domain.Entities.Result", b =>
                {
                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("mate.Domain.Entities.RubricSet", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("mate.Domain.Entities.Run", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("mate.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("ApiKeys");

                    b.Navigation("Documents");

                    b.Navigation("JudgeSettings");

                    b.Navigation("Subscription");

                    b.Navigation("TestSuites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestCase", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("mate.Domain.Entities.TestSuite", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("TestCases");

                    b.Navigation("TestSuiteAgents");
                });
#pragma warning restore 612, 618
        }
    }
}
